name: branch(game_ply_limit)

on:
  push:
    branches: [ game_ply_limit ]
  pull_request:
    branches: [ game_ply_limit ]

jobs:
  macos13:
    strategy:
      matrix:
        arch: ["x86-64-bmi2", "x86-64-modern", "x86-64"]
    runs-on: macos-13
    
    steps:
      - uses: actions/checkout@v4

      - name: make
        run: cd src && make clean && make -j build COMP=gcc ARCH=${{ matrix.arch }} EXE=fairy-stockfish_${{ matrix.arch }} && strip fairy-stockfish_${{ matrix.arch }}

      - uses: actions/upload-artifact@v4
        with:
          name: FSF macos ${{ matrix.arch }}
          path: src/fairy-stockfish_${{ matrix.arch }}

      - name: make largeboards
        run: cd src && make clean && make -j build COMP=gcc ARCH=${{ matrix.arch }} EXE=fairy-stockfish-largeboards_${{ matrix.arch }} largeboards=yes && strip fairy-stockfish-largeboards_${{ matrix.arch }}

      - uses: actions/upload-artifact@v4
        with:
          name: FSF LB macos ${{ matrix.arch }}
          path: src/fairy-stockfish-largeboards_${{ matrix.arch }}

      - name: make all
        if: ${{ matrix.arch == 'x86-64' }}
        run: cd src && make clean && make -j build COMP=gcc ARCH=${{ matrix.arch }} EXE=fairy-stockfish-largeboards-all_${{ matrix.arch }} largeboards=yes all=yes && strip fairy-stockfish-largeboards-all_${{ matrix.arch }}

      - uses: actions/upload-artifact@v4
        if: ${{ matrix.arch == 'x86-64' }}
        with:
          name: FSF LB All macos ${{ matrix.arch }}
          path: src/fairy-stockfish-largeboards-all_${{ matrix.arch }}

  macos14:
    strategy:
      matrix:
        arch: ["apple-silicon"]
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - name: make
        run: cd src && make clean && make -j build COMP=clang ARCH=${{ matrix.arch }} EXE=fairy-stockfish_${{ matrix.arch }} && strip fairy-stockfish_${{ matrix.arch }}

      - uses: actions/upload-artifact@v4
        with:
          name: FSF macos-m1 ${{ matrix.arch }}
          path: src/fairy-stockfish_${{ matrix.arch }}

  windows:
    strategy:
      matrix:
        arch: ["x86-64-bmi2", "x86-64-modern", "x86-64"]
    runs-on: windows-2022

    steps:
      - uses: al-cheb/configure-pagefile-action@v1.2        
        with:        
            minimum-size: 16GB
            maximum-size: 16GB
            disk-root: "C:"

      - uses: actions/checkout@v4

      - name: make
        run: cd src && make clean && make -j build COMP=mingw ARCH=${{ matrix.arch }} EXE=fairy-stockfish_${{ matrix.arch }}.exe && strip fairy-stockfish_${{ matrix.arch }}.exe

      - uses: actions/upload-artifact@v4
        with:
          name: FSF windows ${{ matrix.arch }}
          path: src/fairy-stockfish_${{ matrix.arch }}.exe

      - name: make largeboards
        run: cd src && make clean && make -j build COMP=mingw ARCH=${{ matrix.arch }} EXE=fairy-stockfish-largeboards_${{ matrix.arch }}.exe largeboards=yes && strip fairy-stockfish-largeboards_${{ matrix.arch }}.exe

      - uses: actions/upload-artifact@v4
        with:
          name: FSF LB windows ${{ matrix.arch }}
          path: src/fairy-stockfish-largeboards_${{ matrix.arch }}.exe

      - name: make all
        if: ${{ matrix.arch == 'x86-64' }}
        run: cd src && make clean && make -j build COMP=mingw ARCH=${{ matrix.arch }} EXE=fairy-stockfish-largeboards-all_${{ matrix.arch }}.exe largeboards=yes all=yes && strip fairy-stockfish-largeboards-all_${{ matrix.arch }}.exe

      - uses: actions/upload-artifact@v4
        if: ${{ matrix.arch == 'x86-64' }}
        with:
          name: FSF LB All windows ${{ matrix.arch }}
          path: src/fairy-stockfish-largeboards-all_${{ matrix.arch }}.exe

  linux:
    strategy:
      matrix:
        arch: ["x86-64-bmi2", "x86-64-modern", "x86-64"]
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: make
        run: cd src && make clean && make -j build COMP=gcc ARCH=${{ matrix.arch }} EXE=fairy-stockfish_${{ matrix.arch }} && strip fairy-stockfish_${{ matrix.arch }}

      - uses: actions/upload-artifact@v4
        with:
          name: FSF ubuntu ${{ matrix.arch }}
          path: src/fairy-stockfish_${{ matrix.arch }}

      - name: make largeboards
        run: cd src && make clean && make -j build COMP=gcc ARCH=${{ matrix.arch }} EXE=fairy-stockfish-largeboards_${{ matrix.arch }} largeboards=yes && strip fairy-stockfish-largeboards_${{ matrix.arch }}

      - uses: actions/upload-artifact@v4
        with:
          name: FSF LB linux ${{ matrix.arch }}
          path: src/fairy-stockfish-largeboards_${{ matrix.arch }}

      - name: make all
        if: ${{ matrix.arch == 'x86-64' }}
        run: cd src && make clean && make -j build COMP=gcc ARCH=${{ matrix.arch }} EXE=fairy-stockfish-largeboards-all_${{ matrix.arch }} largeboards=yes all=yes && strip fairy-stockfish-largeboards-all_${{ matrix.arch }}

      - uses: actions/upload-artifact@v4
        if: ${{ matrix.arch == 'x86-64' }}
        with:
          name: FSF LB All linux ${{ matrix.arch }}
          path: src/fairy-stockfish-largeboards-all_${{ matrix.arch }}
