name: branch(game_ply_limit)

on:
  push:
    branches: [ game_ply_limit ]
  pull_request:
    branches: [ game_ply_limit ]

jobs:
  macos13:
    strategy:
      matrix:
        arch: ["x86-64-bmi2", "x86-64-modern", "x86-64"]
    runs-on: macos-13
    env:
      COMPCXX: clang++
      COMP: clang
      NAME: macos
    steps:
      - uses: actions/checkout@v4

      - name: Check compiler
        run: $COMPCXX -v

      - name: make
        run: cd src && make clean && make -j build COMP=$COMP ARCH=${{ matrix.arch }} EXE=fairy-stockfish_${{ matrix.arch }}${{ env.EXT }} && strip fairy-stockfish_${{ matrix.arch }}${{ env.EXT }}

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.NAME }} ${{ matrix.arch }} (FSF)
          path: src/fairy-stockfish_${{ matrix.arch }}${{ env.EXT }}

      - name: make largeboards
        run: cd src && make clean && make -j build COMP=$COMP ARCH=${{ matrix.arch }} EXE=fairy-stockfish-largeboards_${{ matrix.arch }}${{ env.EXT }} largeboards=yes && strip fairy-stockfish-largeboards_${{ matrix.arch }}${{ env.EXT }}

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.NAME }} ${{ matrix.arch }} (FSF LB)
          path: src/fairy-stockfish-largeboards_${{ matrix.arch }}${{ env.EXT }}

      - name: make all
        if: ${{ matrix.arch == 'x86-64' }}
        run: cd src && make clean && make -j build COMP=$COMP ARCH=${{ matrix.arch }} EXE=fairy-stockfish-largeboards-all_${{ matrix.arch }}${{ env.EXT }} largeboards=yes all=yes && strip fairy-stockfish-largeboards-all_${{ matrix.arch }}${{ env.EXT }}

      - uses: actions/upload-artifact@v4
        if: ${{ matrix.arch == 'x86-64' }}
        with:
          name: ${{ env.NAME }} ${{ matrix.arch }} (FSF LB All)
          path: src/fairy-stockfish-largeboards-all_${{ matrix.arch }}${{ env.EXT }}

  macos14:
    strategy:
      matrix:
        arch: ["apple-silicon"]
    runs-on: macos-14

    env:
      COMPCXX: clang++
      COMP: clang
      NAME: macos-m1

    steps:
      - uses: actions/checkout@v4

      - name: Check compiler
        run: $COMPCXX -v

      - name: make
        run: cd src && make clean && make -j build COMP=$COMP ARCH=${{ matrix.arch }} EXE=fairy-stockfish_${{ matrix.arch }} && strip fairy-stockfish_${{ matrix.arch }}

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.NAME }} ${{ matrix.arch }} (FSF)
          path: src/fairy-stockfish_${{ matrix.arch }}

  windows:
    strategy:
      matrix:
        arch: ["x86-64-bmi2", "x86-64-modern", "x86-64"]
    runs-on: windows-2022

    env:
      COMPCXX: g++
      COMP: mingw
      EXT: .exe
      NAME: windows

    steps:
      - uses: al-cheb/configure-pagefile-action@v1.2        
        with:        
            minimum-size: 16GB
            maximum-size: 16GB
            disk-root: "C:"

      - uses: actions/checkout@v4

      - name: make
        run: cd src && make clean && make -j build COMP=$COMP ARCH=${{ matrix.arch }} EXE=fairy-stockfish_${{ matrix.arch }}${{ env.EXT }} && strip fairy-stockfish_${{ matrix.arch }}${{ env.EXT }}

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.NAME }} ${{ matrix.arch }} (FSF)
          path: src/fairy-stockfish_${{ matrix.arch }}${{ env.EXT }}

      - name: make largeboards
        run: cd src && make clean && make -j build COMP=$COMP ARCH=${{ matrix.arch }} EXE=fairy-stockfish-largeboards_${{ matrix.arch }}${{ env.EXT }} largeboards=yes && strip fairy-stockfish-largeboards_${{ matrix.arch }}${{ env.EXT }}

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.NAME }} ${{ matrix.arch }} (FSF LB)
          path: src/fairy-stockfish-largeboards_${{ matrix.arch }}${{ env.EXT }}

      - name: make all
        if: ${{ matrix.arch == 'x86-64' }}
        run: cd src && make clean && make -j build COMP=$COMP ARCH=${{ matrix.arch }} EXE=fairy-stockfish-largeboards-all_${{ matrix.arch }}${{ env.EXT }} largeboards=yes all=yes && strip fairy-stockfish-largeboards-all_${{ matrix.arch }}${{ env.EXT }}

      - uses: actions/upload-artifact@v4
        if: ${{ matrix.arch == 'x86-64' }}
        with:
          name: ${{ env.NAME }} ${{ matrix.arch }} (FSF LB All)
          path: src/fairy-stockfish-largeboards-all_${{ matrix.arch }}${{ env.EXT }}

  linux:
    strategy:
      matrix:
        arch: ["x86-64-bmi2", "x86-64-modern", "x86-64"]
    runs-on: ubuntu-20.04
    env:
      COMPCXX: g++
      COMP: gcc
      EXT: ''
      NAME: ubuntu

    steps:
      - uses: actions/checkout@v4

      - name: make
        run: cd src && make clean && make -j build COMP=${{ env.COMP }} ARCH=${{ matrix.arch }} EXE=fairy-stockfish_${{ matrix.arch }}${{ env.EXT }} && strip fairy-stockfish_${{ matrix.arch }}${{ env.$EXT }}

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.NAME }} ${{ matrix.arch }} (FSF)
          path: src/fairy-stockfish_${{ matrix.arch }}${{ env.$EXT }}

      - name: make largeboards
        run: cd src && make clean && make -j build COMP=${{ env.COMP }} ARCH=${{ matrix.arch }} EXE=fairy-stockfish-largeboards_${{ matrix.arch }}$EXT largeboards=yes && strip fairy-stockfish-largeboards_${{ matrix.arch }}$EXT

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.NAME }} ${{ matrix.arch }} (FSF LB)
          path: src/fairy-stockfish-largeboards_${{ matrix.arch }}$EXT

      - name: make all
        if: ${{ matrix.arch == 'x86-64' }}
        run: cd src && make clean && make -j build COMP=${{ env.COMP }} ARCH=${{ matrix.arch }} EXE=fairy-stockfish-largeboards-all_${{ matrix.arch }}$EXT largeboards=yes all=yes && strip fairy-stockfish-largeboards-all_${{ matrix.arch }}$EXT

      - uses: actions/upload-artifact@v4
        if: ${{ matrix.arch == 'x86-64' }}
        with:
          name: ${{ env.NAME }} ${{ matrix.arch }} (FSF LB All)
          path: src/fairy-stockfish-largeboards-all_${{ matrix.arch }}$EXT
