name: branch(game_ply_limit)

on:
  push:
    branches: [ game_ply_limit ]
  pull_request:
    branches: [ game_ply_limit ]

jobs:
  windows:
    strategy:
      matrix:
        arch: ["x86-64-bmi2", "x86-64-modern", "x86-64"]
    runs-on: windows-2022

    steps:
      - uses: al-cheb/configure-pagefile-action@v1.2        
        with:        
            minimum-size: 16GB
            maximum-size: 16GB
            disk-root: "C:"

      - uses: actions/checkout@v3

      - name: make
        run: cd src && make clean && make -j build COMP=mingw ARCH=${{ matrix.arch }} EXE=fairy-stockfish_${{ matrix.arch }}.exe && strip fairy-stockfish_${{ matrix.arch }}.exe

      - uses: actions/upload-artifact@v4
        with:
          name: fairy-stockfish_${{ matrix.arch }}_windows
          path: src/fairy-stockfish_${{ matrix.arch }}.exe

      - name: make largeboards
        run: cd src && make clean && make -j build COMP=mingw ARCH=${{ matrix.arch }} EXE=fairy-stockfish-largeboards_${{ matrix.arch }}.exe largeboards=yes && strip fairy-stockfish-largeboards_${{ matrix.arch }}.exe

      - uses: actions/upload-artifact@v4
        with:
          name: fairy-stockfish-largeboards_${{ matrix.arch }}_windows
          path: src/fairy-stockfish-largeboards_${{ matrix.arch }}.exe

      - name: make all
        if: ${{ matrix.arch == 'x86-64' }}
        run: cd src && make clean && make -j build COMP=mingw ARCH=${{ matrix.arch }} EXE=fairy-stockfish-largeboards-all_${{ matrix.arch }}.exe largeboards=yes all=yes && strip fairy-stockfish-all_${{ matrix.arch }}.exe

      - uses: actions/upload-artifact@v4
        with:
          name: fairy-stockfish-largeboards-all_${{ matrix.arch }}_windows
          path: src/fairy-stockfish-largeboards-all_${{ matrix.arch }}.exe

  linux:
    strategy:
      matrix:
        arch: ["x86-64-bmi2", "x86-64-modern", "x86-64"]
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: make
        run: cd src && make clean && make -j build COMP=gcc ARCH=${{ matrix.arch }} EXE=fairy-stockfish_${{ matrix.arch }} && strip fairy-stockfish_${{ matrix.arch }}

      - uses: actions/upload-artifact@v4
        with:
          name: fairy-stockfish_${{ matrix.arch }}_linux
          path: src/fairy-stockfish_${{ matrix.arch }}

      - name: make largeboards
        run: cd src && make clean && make -j build COMP=gcc ARCH=${{ matrix.arch }} EXE=fairy-stockfish-largeboards_${{ matrix.arch }} largeboards=yes && strip fairy-stockfish-largeboards_${{ matrix.arch }}

      - uses: actions/upload-artifact@v4
        with:
          name: fairy-stockfish-largeboards_${{ matrix.arch }}_linux
          path: src/fairy-stockfish-largeboards_${{ matrix.arch }}

      - name: make all
        if: ${{ matrix.arch == 'x86-64' }}
        run: cd src && make clean && make -j build COMP=gcc ARCH=${{ matrix.arch }} EXE=fairy-stockfish-largeboards-all_${{ matrix.arch }} largeboards=yes all=yes && strip fairy-stockfish-all_${{ matrix.arch }}

      - uses: actions/upload-artifact@v4
        with:
          name: fairy-stockfish-largeboards-all_${{ matrix.arch }}_linux
          path: src/fairy-stockfish-largeboards-all_${{ matrix.arch }}
