name: branch(game_ply_limit)

env:
  EXE_NAME_STD: fairy-stockfish
  EXE_NAME_LB:  fairy-stockfish-largeboards
  EXE_NAME_ALL: fairy-stockfish-largeboards-all

on:
  push:
    branches: [ game_ply_limit ]
  pull_request:
    branches: [ game_ply_limit ]
  workflow_dispatch:
    branches: [ game_ply_limit ]

jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
     - uses: actions/checkout@v4
       
     - name: Set matrix data
       id: set-matrix
       run: |
            echo "build matrix:" >> $GITHUB_STEP_SUMMARY
            echo "matrix=$(jq -c . < .github/workflows/matrix.json)" >> $GITHUB_STEP_SUMMARY
            echo "matrix=$(jq -c . < .github/workflows/matrix.json)" >> $GITHUB_OUTPUT

  build:
    needs: configure    
    runs-on: ${{matrix.run_os}}
    strategy:
      matrix: ${{ fromJson(needs.configure.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4

      - name: Check compiler
        run: ${{ matrix.COMPCXX }} -v

      - name: make
        if: ${{ matrix.build_std == true }}
        run: cd src && make clean && make -j build COMP=${{ matrix.COMP }} ARCH=${{ matrix.arch }} EXE=${{ env.EXE_NAME_STD }}_${{ matrix.arch }}${{ matrix.EXT }} && strip ${{ env.EXE_NAME_STD }}_${{ matrix.arch }}${{ matrix.EXT }}

      - uses: actions/upload-artifact@v4
        if: ${{ matrix.build_std == true }}
        with:
          name: ${{ matrix.NAME }} ${{ env.EXE_NAME_STD }}_${{ matrix.arch }}
          path: src/${{ env.EXE_NAME_STD }}_${{ matrix.arch }}${{ matrix.EXT }}

      - name: make largeboards
        if: ${{ matrix.build_lb == true }}
        run: cd src && make clean && make -j build COMP=${{ matrix.COMP }} ARCH=${{ matrix.arch }} EXE=${{ env.EXE_NAME_LB }}_${{ matrix.arch }}${{ matrix.EXT }} largeboards=yes && strip ${{ env.EXE_NAME_LB }}_${{ matrix.arch }}${{ matrix.EXT }}

      - uses: actions/upload-artifact@v4
        if: ${{ matrix.build_lb == true }}
        with:
          name: ${{ matrix.NAME }} ${{ env.EXE_NAME_LB }}_${{ matrix.arch }}
          path: src/${{ env.EXE_NAME_LB }}_${{ matrix.arch }}${{ matrix.EXT }}

      - name: make all
        if: ${{ matrix.build_all == true }}
        run: cd src && make clean && make -j build COMP=${{ matrix.COMP }} ARCH=${{ matrix.arch }} EXE=${{ env.EXE_NAME_ALL }}_${{ matrix.arch }}${{ matrix.EXT }} largeboards=yes all=yes && strip ${{ env.EXE_NAME_ALL }}_${{ matrix.arch }}${{ matrix.EXT }}

      - uses: actions/upload-artifact@v4
        if: ${{ matrix.build_all == true }}
        with:
          name: ${{ matrix.NAME }} ${{ env.EXE_NAME_ALL }}_${{ matrix.arch }}
          path: src/${{ env.EXE_NAME_ALL }}_${{ matrix.arch }}${{ matrix.EXT }}
