name: branch(game_ply_limit)

on:
  push:
    branches: [ game_ply_limit ]
  pull_request:
    branches: [ game_ply_limit ]

jobs:
  windows:
    strategy:
      matrix:
        arch: ["x86-64-bmi2", "x86-64-modern", "x86-64"]
    runs-on: windows-2022

    steps:
      - uses: al-cheb/configure-pagefile-action@v1.2        
        with:        
            minimum-size: 16GB
            maximum-size: 16GB
            disk-root: "C:"

      - uses: actions/checkout@v3

      - name: make
        run: cd src && make clean && make -j build COMP=mingw ARCH=${{ matrix.arch }} EXE=fairy-stockfish_${{ matrix.arch }}.exe && strip fairy-stockfish_${{ matrix.arch }}.exe

      - name: make largeboards
        run: cd src && make clean && make -j build COMP=mingw ARCH=${{ matrix.arch }} EXE=fairy-stockfish-largeboards_${{ matrix.arch }}.exe largeboards=yes && strip fairy-stockfish-largeboards_${{ matrix.arch }}.exe

      - name: make all
        if: ${{ matrix.arch == 'x86-64' }}
        run: cd src && make clean && make -j build COMP=mingw ARCH=${{ matrix.arch }} EXE=fairy-stockfish-all_${{ matrix.arch }}.exe largeboards=yes all=yes && strip fairy-stockfish-all_${{ matrix.arch }}.exe

      - uses: actions/upload-artifact@v4
        with:
          name: fsf_all_win64
          path: D:/a/Fairy-Stockfish/Fairy-Stockfish/src/fairy-stockfish-all_x86-64.exe

      - uses: actions/upload-artifact@v4
        with:
          name: fsf_lb_win64
          path: D:/a/Fairy-Stockfish/Fairy-Stockfish/src/fairy-stockfish-largeboards_x86-64.exe

      - uses: actions/upload-artifact@v4
        with:
          name: fsf_lb_bmi2_win64
          path: D:/a/Fairy-Stockfish/Fairy-Stockfish/src/fairy-stockfish-largeboards_x86-64-bmi2.exe

      - uses: actions/upload-artifact@v4
        with:
          name: fsf_lb_modern_win64
          path: D:/a/Fairy-Stockfish/Fairy-Stockfish/src/fairy-stockfish-largeboards_x86-64-modern.exe

      - uses: actions/upload-artifact@v4
        with:
          name: fsf_win64
          path: D:/a/Fairy-Stockfish/Fairy-Stockfish/src/fairy-stockfish_x86-64.exe

      - uses: actions/upload-artifact@v4
        with:
          name: fsf_bmi2_win64
          path: D:/a/Fairy-Stockfish/Fairy-Stockfish/src/fairy-stockfish_x86-64-bmi2.exe

      - uses: actions/upload-artifact@v4
        with:
          name: fsf_modern_win64
          path: D:/a/Fairy-Stockfish/Fairy-Stockfish/src/fairy-stockfish_x86-64-modern.exe

  linux:
    strategy:
      matrix:
        arch: ["x86-64-bmi2", "x86-64-modern", "x86-64"]
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: make
        run: cd src && make clean && make -j build COMP=gcc ARCH=${{ matrix.arch }} EXE=fairy-stockfish_${{ matrix.arch }} && strip fairy-stockfish_${{ matrix.arch }}

      - name: make largeboards
        run: cd src && make clean && make -j build COMP=gcc ARCH=${{ matrix.arch }} EXE=fairy-stockfish-largeboards_${{ matrix.arch }} largeboards=yes && strip fairy-stockfish-largeboards_${{ matrix.arch }}

      - name: make all
        if: ${{ matrix.arch == 'x86-64' }}
        run: cd src && make clean && make -j build COMP=gcc ARCH=${{ matrix.arch }} EXE=fairy-stockfish-all_${{ matrix.arch }} largeboards=yes all=yes && strip fairy-stockfish-all_${{ matrix.arch }}

      - uses: actions/upload-artifact@v4
        with:
          name: fairy-stockfish-all_x86-64_linux
          path: D:/a/Fairy-Stockfish/Fairy-Stockfish/src/fairy-stockfish-all_x86-64

      - uses: actions/upload-artifact@v4
        with:
          name: fairy-stockfish-largeboards_x86-64_linux
          path: D:/a/Fairy-Stockfish/Fairy-Stockfish/src/fairy-stockfish-largeboards_x86-64

      - uses: actions/upload-artifact@v4
        with:
          name: fairy-stockfish-largeboards_x86-64-bmi2_linux
          path: D:/a/Fairy-Stockfish/Fairy-Stockfish/src/fairy-stockfish-largeboards_x86-64-bmi2

      - uses: actions/upload-artifact@v4
        with:
          name: fairy-stockfish-largeboards_x86-64-modern_linux
          path: D:/a/Fairy-Stockfish/Fairy-Stockfish/src/fairy-stockfish-largeboards_x86-64-modern

      - uses: actions/upload-artifact@v4
        with:
          name: fairy-stockfish_x86-64_linux
          path: D:/a/Fairy-Stockfish/Fairy-Stockfish/src/fairy-stockfish_x86-64

      - uses: actions/upload-artifact@v4
        with:
          name: fairy-stockfish_x86-64-bmi2_linux
          path: D:/a/Fairy-Stockfish/Fairy-Stockfish/src/fairy-stockfish_x86-64-bmi2

      - uses: actions/upload-artifact@v4
        with:
          name: fairy-stockfish_x86-64-modern_linux
          path: D:/a/Fairy-Stockfish/Fairy-Stockfish/src/fairy-stockfish_x86-64-modern
